apiVersion: openeoe.k8s.io/v1alpha1
kind: Migration
metadata:
  name: migrations
spec:
  migrationServiceSource:
  - sourceCluster: cluster1
    targetCluster: cluster2
    nameSpace: testmig
    serviceName: testim
    migrationSource:
    - resourceName: testim-dp
      resourceType: Deployment
    - resourceName: testim-sv
      resourceType: Service
    - resourceName: testim-pv
      resourceType: PersistentVolume
    - resourceName: testim-pvc
      resourceType: PersistentVolumeClaim
