apiVersion: openeoe.k8s.io/v1alpha1
kind: Migration
metadata:
  name: migrations3
spec:
  migrationServiceSource:
  - sourceCluster: cluster1
    targetCluster: cluster2
    nameSpace: openeoe
    serviceName: openeoe-deploy
    migrationSource:
    - resourceName: openeoe-deployment
      resourceType: Deployment
